// ============================================================
// lib/constants/surah.ts
// Daftar 114 surah Al-Qur'an — hardcoded (keputusan final MR-05)
// ============================================================

export interface Surah {
  nomor: number
  nama:  string
  latin: string
  ayat:  number
}

export const SURAH_LIST: Surah[] = [
  { nomor: 1,   nama: 'الفاتحة',       latin: 'Al-Fatihah',       ayat: 7   },
  { nomor: 2,   nama: 'البقرة',         latin: 'Al-Baqarah',       ayat: 286 },
  { nomor: 3,   nama: 'آل عمران',       latin: 'Ali Imran',        ayat: 200 },
  { nomor: 4,   nama: 'النساء',         latin: 'An-Nisa',          ayat: 176 },
  { nomor: 5,   nama: 'المائدة',        latin: 'Al-Maidah',        ayat: 120 },
  { nomor: 6,   nama: 'الأنعام',        latin: 'Al-An\'am',        ayat: 165 },
  { nomor: 7,   nama: 'الأعراف',        latin: 'Al-A\'raf',        ayat: 206 },
  { nomor: 8,   nama: 'الأنفال',        latin: 'Al-Anfal',         ayat: 75  },
  { nomor: 9,   nama: 'التوبة',         latin: 'At-Taubah',        ayat: 129 },
  { nomor: 10,  nama: 'يونس',           latin: 'Yunus',            ayat: 109 },
  { nomor: 11,  nama: 'هود',            latin: 'Hud',              ayat: 123 },
  { nomor: 12,  nama: 'يوسف',           latin: 'Yusuf',            ayat: 111 },
  { nomor: 13,  nama: 'الرعد',          latin: 'Ar-Ra\'d',         ayat: 43  },
  { nomor: 14,  nama: 'إبراهيم',        latin: 'Ibrahim',          ayat: 52  },
  { nomor: 15,  nama: 'الحجر',          latin: 'Al-Hijr',          ayat: 99  },
  { nomor: 16,  nama: 'النحل',          latin: 'An-Nahl',          ayat: 128 },
  { nomor: 17,  nama: 'الإسراء',        latin: 'Al-Isra',          ayat: 111 },
  { nomor: 18,  nama: 'الكهف',          latin: 'Al-Kahf',          ayat: 110 },
  { nomor: 19,  nama: 'مريم',           latin: 'Maryam',           ayat: 98  },
  { nomor: 20,  nama: 'طه',             latin: 'Ta Ha',            ayat: 135 },
  { nomor: 21,  nama: 'الأنبياء',       latin: 'Al-Anbiya',        ayat: 112 },
  { nomor: 22,  nama: 'الحج',           latin: 'Al-Hajj',          ayat: 78  },
  { nomor: 23,  nama: 'المؤمنون',       latin: 'Al-Mu\'minun',     ayat: 118 },
  { nomor: 24,  nama: 'النور',          latin: 'An-Nur',           ayat: 64  },
  { nomor: 25,  nama: 'الفرقان',        latin: 'Al-Furqan',        ayat: 77  },
  { nomor: 26,  nama: 'الشعراء',        latin: 'Asy-Syu\'ara',     ayat: 227 },
  { nomor: 27,  nama: 'النمل',          latin: 'An-Naml',          ayat: 93  },
  { nomor: 28,  nama: 'القصص',          latin: 'Al-Qasas',         ayat: 88  },
  { nomor: 29,  nama: 'العنكبوت',       latin: 'Al-Ankabut',       ayat: 69  },
  { nomor: 30,  nama: 'الروم',          latin: 'Ar-Rum',           ayat: 60  },
  { nomor: 31,  nama: 'لقمان',          latin: 'Luqman',           ayat: 34  },
  { nomor: 32,  nama: 'السجدة',         latin: 'As-Sajdah',        ayat: 30  },
  { nomor: 33,  nama: 'الأحزاب',        latin: 'Al-Ahzab',         ayat: 73  },
  { nomor: 34,  nama: 'سبأ',            latin: 'Saba',             ayat: 54  },
  { nomor: 35,  nama: 'فاطر',           latin: 'Fatir',            ayat: 45  },
  { nomor: 36,  nama: 'يس',             latin: 'Ya Sin',           ayat: 83  },
  { nomor: 37,  nama: 'الصافات',        latin: 'As-Saffat',        ayat: 182 },
  { nomor: 38,  nama: 'ص',              latin: 'Sad',              ayat: 88  },
  { nomor: 39,  nama: 'الزمر',          latin: 'Az-Zumar',         ayat: 75  },
  { nomor: 40,  nama: 'غافر',           latin: 'Ghafir',           ayat: 85  },
  { nomor: 41,  nama: 'فصلت',           latin: 'Fussilat',         ayat: 54  },
  { nomor: 42,  nama: 'الشورى',         latin: 'Asy-Syura',        ayat: 53  },
  { nomor: 43,  nama: 'الزخرف',         latin: 'Az-Zukhruf',       ayat: 89  },
  { nomor: 44,  nama: 'الدخان',         latin: 'Ad-Dukhan',        ayat: 59  },
  { nomor: 45,  nama: 'الجاثية',        latin: 'Al-Jasiyah',       ayat: 37  },
  { nomor: 46,  nama: 'الأحقاف',        latin: 'Al-Ahqaf',         ayat: 35  },
  { nomor: 47,  nama: 'محمد',           latin: 'Muhammad',         ayat: 38  },
  { nomor: 48,  nama: 'الفتح',          latin: 'Al-Fath',          ayat: 29  },
  { nomor: 49,  nama: 'الحجرات',        latin: 'Al-Hujurat',       ayat: 18  },
  { nomor: 50,  nama: 'ق',              latin: 'Qaf',              ayat: 45  },
  { nomor: 51,  nama: 'الذاريات',       latin: 'Az-Zariyat',       ayat: 60  },
  { nomor: 52,  nama: 'الطور',          latin: 'At-Tur',           ayat: 49  },
  { nomor: 53,  nama: 'النجم',          latin: 'An-Najm',          ayat: 62  },
  { nomor: 54,  nama: 'القمر',          latin: 'Al-Qamar',         ayat: 55  },
  { nomor: 55,  nama: 'الرحمن',         latin: 'Ar-Rahman',        ayat: 78  },
  { nomor: 56,  nama: 'الواقعة',        latin: 'Al-Waqi\'ah',      ayat: 96  },
  { nomor: 57,  nama: 'الحديد',         latin: 'Al-Hadid',         ayat: 29  },
  { nomor: 58,  nama: 'المجادلة',       latin: 'Al-Mujadilah',     ayat: 22  },
  { nomor: 59,  nama: 'الحشر',          latin: 'Al-Hasyr',         ayat: 24  },
  { nomor: 60,  nama: 'الممتحنة',       latin: 'Al-Mumtahanah',    ayat: 13  },
  { nomor: 61,  nama: 'الصف',           latin: 'As-Saf',           ayat: 14  },
  { nomor: 62,  nama: 'الجمعة',         latin: 'Al-Jumu\'ah',      ayat: 11  },
  { nomor: 63,  nama: 'المنافقون',      latin: 'Al-Munafiqun',     ayat: 11  },
  { nomor: 64,  nama: 'التغابن',        latin: 'At-Tagabun',       ayat: 18  },
  { nomor: 65,  nama: 'الطلاق',         latin: 'At-Talaq',         ayat: 12  },
  { nomor: 66,  nama: 'التحريم',        latin: 'At-Tahrim',        ayat: 12  },
  { nomor: 67,  nama: 'الملك',          latin: 'Al-Mulk',          ayat: 30  },
  { nomor: 68,  nama: 'القلم',          latin: 'Al-Qalam',         ayat: 52  },
  { nomor: 69,  nama: 'الحاقة',         latin: 'Al-Haqqah',        ayat: 52  },
  { nomor: 70,  nama: 'المعارج',        latin: 'Al-Ma\'arij',      ayat: 44  },
  { nomor: 71,  nama: 'نوح',            latin: 'Nuh',              ayat: 28  },
  { nomor: 72,  nama: 'الجن',           latin: 'Al-Jinn',          ayat: 28  },
  { nomor: 73,  nama: 'المزمل',         latin: 'Al-Muzzammil',     ayat: 20  },
  { nomor: 74,  nama: 'المدثر',         latin: 'Al-Muddassir',     ayat: 56  },
  { nomor: 75,  nama: 'القيامة',        latin: 'Al-Qiyamah',       ayat: 40  },
  { nomor: 76,  nama: 'الإنسان',        latin: 'Al-Insan',         ayat: 31  },
  { nomor: 77,  nama: 'المرسلات',       latin: 'Al-Mursalat',      ayat: 50  },
  { nomor: 78,  nama: 'النبأ',          latin: 'An-Naba',          ayat: 40  },
  { nomor: 79,  nama: 'النازعات',       latin: 'An-Nazi\'at',      ayat: 46  },
  { nomor: 80,  nama: 'عبس',            latin: 'Abasa',            ayat: 42  },
  { nomor: 81,  nama: 'التكوير',        latin: 'At-Takwir',        ayat: 29  },
  { nomor: 82,  nama: 'الانفطار',       latin: 'Al-Infitar',       ayat: 19  },
  { nomor: 83,  nama: 'المطففين',       latin: 'Al-Mutaffifin',    ayat: 36  },
  { nomor: 84,  nama: 'الانشقاق',       latin: 'Al-Insyiqaq',      ayat: 25  },
  { nomor: 85,  nama: 'البروج',         latin: 'Al-Buruj',         ayat: 22  },
  { nomor: 86,  nama: 'الطارق',         latin: 'At-Tariq',         ayat: 17  },
  { nomor: 87,  nama: 'الأعلى',         latin: 'Al-A\'la',         ayat: 19  },
  { nomor: 88,  nama: 'الغاشية',        latin: 'Al-Ghasyiyah',     ayat: 26  },
  { nomor: 89,  nama: 'الفجر',          latin: 'Al-Fajr',          ayat: 30  },
  { nomor: 90,  nama: 'البلد',          latin: 'Al-Balad',         ayat: 20  },
  { nomor: 91,  nama: 'الشمس',          latin: 'Asy-Syams',        ayat: 15  },
  { nomor: 92,  nama: 'الليل',          latin: 'Al-Lail',          ayat: 21  },
  { nomor: 93,  nama: 'الضحى',          latin: 'Ad-Duha',          ayat: 11  },
  { nomor: 94,  nama: 'الشرح',          latin: 'Al-Insyirah',      ayat: 8   },
  { nomor: 95,  nama: 'التين',          latin: 'At-Tin',           ayat: 8   },
  { nomor: 96,  nama: 'العلق',          latin: 'Al-Alaq',          ayat: 19  },
  { nomor: 97,  nama: 'القدر',          latin: 'Al-Qadr',          ayat: 5   },
  { nomor: 98,  nama: 'البينة',         latin: 'Al-Bayyinah',      ayat: 8   },
  { nomor: 99,  nama: 'الزلزلة',        latin: 'Az-Zalzalah',      ayat: 8   },
  { nomor: 100, nama: 'العاديات',       latin: 'Al-Adiyat',        ayat: 11  },
  { nomor: 101, nama: 'القارعة',        latin: 'Al-Qari\'ah',      ayat: 11  },
  { nomor: 102, nama: 'التكاثر',        latin: 'At-Takasur',       ayat: 8   },
  { nomor: 103, nama: 'العصر',          latin: 'Al-Asr',           ayat: 3   },
  { nomor: 104, nama: 'الهمزة',         latin: 'Al-Humazah',       ayat: 9   },
  { nomor: 105, nama: 'الفيل',          latin: 'Al-Fil',           ayat: 5   },
  { nomor: 106, nama: 'قريش',           latin: 'Quraisy',          ayat: 4   },
  { nomor: 107, nama: 'الماعون',        latin: 'Al-Ma\'un',        ayat: 7   },
  { nomor: 108, nama: 'الكوثر',         latin: 'Al-Kausar',        ayat: 3   },
  { nomor: 109, nama: 'الكافرون',       latin: 'Al-Kafirun',       ayat: 6   },
  { nomor: 110, nama: 'النصر',          latin: 'An-Nasr',          ayat: 3   },
  { nomor: 111, nama: 'المسد',          latin: 'Al-Masad',         ayat: 5   },
  { nomor: 112, nama: 'الإخلاص',        latin: 'Al-Ikhlas',        ayat: 4   },
  { nomor: 113, nama: 'الفلق',          latin: 'Al-Falaq',         ayat: 5   },
  { nomor: 114, nama: 'الناس',          latin: 'An-Nas',           ayat: 6   },
]

// Helper: cari surah berdasarkan nama latin (case-insensitive)
export function searchSurah(query: string): Surah[] {
  if (!query.trim()) return SURAH_LIST
  const q = query.toLowerCase()
  return SURAH_LIST.filter(
    s =>
      s.latin.toLowerCase().includes(q) ||
      s.nama.includes(query) ||
      String(s.nomor).startsWith(q)
  )
}
